2017-05-31 12:02:55,942 ERROR 33120 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 33120
hostname: xiaomo

2017-05-31 12:05:59,438 ERROR 37168 [-/127.0.0.1/-/24ms POST /api/myaccount/beanReturnList] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'log_uid' in 'where clause'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT COUNT(*) as total FROM data_user_bean_return WHERE log_uid='62'
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlState: '42S22'
index: 0
name: 'ER_BAD_FIELD_ERRORError'
pid: 37168
hostname: xiaomo

2017-05-31 12:06:35,528 ERROR 37380 [-/127.0.0.1/-/45ms POST /api/myaccount/beanReturnList] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'return_id' in 'field list'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT return_id,return_uid,return_beans,return_money,return_account_type,return_create_time,return_finish_time,return_status FROM data_user_bean_log  WHERE return_uid = '62' ORDER BY return_id DESC LIMIT 0,1
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlState: '42S22'
index: 0
name: 'ER_BAD_FIELD_ERRORError'
pid: 37380
hostname: xiaomo

2017-05-31 12:09:12,314 ERROR 36920 [-/127.0.0.1/-/24ms POST /api/myaccount/beanReturnList] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'return_id' in 'field list'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT return_id,return_uid,return_beans,return_money,return_account_type,return_create_time,return_finish_time,return_status FROM data_user_bean_log  WHERE return_uid = 62 ORDER BY return_id DESC LIMIT 0,1
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlState: '42S22'
index: 0
name: 'ER_BAD_FIELD_ERRORError'
pid: 36920
hostname: xiaomo

2017-05-31 12:09:13,732 ERROR 36920 [-/127.0.0.1/-/8ms POST /api/myaccount/beanReturnList] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'return_id' in 'field list'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: SELECT return_id,return_uid,return_beans,return_money,return_account_type,return_create_time,return_finish_time,return_status FROM data_user_bean_log  WHERE return_uid = 62 ORDER BY return_id DESC LIMIT 0,1
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlState: '42S22'
index: 0
name: 'ER_BAD_FIELD_ERRORError'
pid: 36920
hostname: xiaomo

2017-05-31 13:59:41,150 ERROR 33120 nodejs.ClusterClientNoResponseError: client no response in 2256637ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:72:23)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 33120
hostname: xiaomo

2017-05-31 13:59:47,870 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 13:59:53,651 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:00:01,652 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:00:09,652 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:00:17,652 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:00:25,653 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:00:33,653 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:00:41,654 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:00:49,654 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:00:57,656 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:01:05,692 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:01:13,694 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:01:21,694 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:01:29,695 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:01:37,694 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:01:45,697 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:01:53,697 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:02:01,708 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:02:09,698 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

2017-05-31 14:02:17,698 ERROR 33120 nodejs.ClusterRequestTypeError: unsupport data type: register_channel
    at Leader._handleRequest (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:354:23)
    at Connection.conn.on (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:261:43)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at process.nextTick (E:\nodejs\sumi-server\node_modules\cluster-client\lib\connection.js:174:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'ClusterRequestTypeError'
pid: 33120
hostname: xiaomo

