2017-05-23 11:19:54,155 ERROR 18468 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column '474adae1f0d5299ff7c0cfee4e19293a' in 'field list'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: UPDATE data_user SET user_token = 474adae1f0d5299ff7c0cfee4e19293a,user_last_login=NOW() WHERE user_id = 62
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlState: '42S22'
index: 0
name: 'unhandledRejectionError'
pid: 18468
hostname: xiaomo

2017-05-23 11:20:32,567 ERROR 19552 [-/127.0.0.1/-/35ms POST /api/login/login] nodejs.ReferenceError: userinfo is not defined
    at LoginController.login (E:\nodejs\sumi-server\app\controller\login.js:89:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 19552
hostname: xiaomo

2017-05-23 11:21:08,648 ERROR 19736 [-/127.0.0.1/-/30ms POST /api/login/login] nodejs.ReferenceError: userinfo is not defined
    at LoginController.login (E:\nodejs\sumi-server\app\controller\login.js:89:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 19736
hostname: xiaomo

2017-05-23 11:21:10,227 ERROR 19736 [-/127.0.0.1/-/11ms POST /api/login/login] nodejs.ReferenceError: userinfo is not defined
    at LoginController.login (E:\nodejs\sumi-server\app\controller\login.js:89:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 19736
hostname: xiaomo

2017-05-23 11:21:32,514 ERROR 19876 [-/127.0.0.1/-/29ms POST /api/login/login] nodejs.ReferenceError: userinfo is not defined
    at LoginController.login (E:\nodejs\sumi-server\app\controller\login.js:89:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 19876
hostname: xiaomo

2017-05-23 11:21:51,732 ERROR 19980 [-/127.0.0.1/-/28ms POST /api/login/login] nodejs.ReferenceError: userinfo is not defined
    at LoginController.login (E:\nodejs\sumi-server\app\controller\login.js:80:20)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 19980
hostname: xiaomo

2017-05-23 11:22:07,312 ERROR 20060 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column '322d1d1938056d6f0987d930e1150fe9' in 'field list'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: UPDATE data_user SET user_token = 322d1d1938056d6f0987d930e1150fe9,user_last_login=NOW() WHERE user_id = 62
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlState: '42S22'
index: 0
name: 'unhandledRejectionError'
pid: 20060
hostname: xiaomo

2017-05-23 11:22:45,596 ERROR 16592 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column 'f1c802514b324977575ed7e20dc45200' in 'field list'
    at Query.Sequence._packetToError (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\nodejs\sumi-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\nodejs\sumi-server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Pool.query (E:\nodejs\sumi-server\node_modules\mysql\lib\Pool.js:199:23)
    at E:\nodejs\sumi-server\node_modules\pify\index.js:29:7
    at Pool.<anonymous> (E:\nodejs\sumi-server\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\nodejs\sumi-server\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSClient.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    sql: UPDATE data_user SET user_token = f1c802514b324977575ed7e20dc45200,user_last_login=NOW() WHERE user_id = 62
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlState: '42S22'
index: 0
name: 'unhandledRejectionError'
pid: 16592
hostname: xiaomo

2017-05-23 11:33:34,173 ERROR 16180 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 16180
hostname: xiaomo

2017-05-23 11:41:57,785 ERROR 16180 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 16180
hostname: xiaomo

2017-05-23 11:42:03,901 ERROR 16180 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 16180
hostname: xiaomo

2017-05-23 11:43:59,952 ERROR 16180 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 16180
hostname: xiaomo

2017-05-23 11:47:09,760 ERROR 16180 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 16180
hostname: xiaomo

2017-05-23 13:56:57,556 ERROR 16180 nodejs.ClusterClientNoResponseError: client no response in 4313782ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\nodejs\sumi-server\node_modules\cluster-client\lib\leader.js:72:23)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 16180
hostname: xiaomo

2017-05-23 14:34:20,626 ERROR 4384 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4384
hostname: xiaomo

2017-05-23 14:53:31,343 ERROR 4384 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4384
hostname: xiaomo

2017-05-23 14:54:16,133 ERROR 4384 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4384
hostname: xiaomo

2017-05-23 14:54:29,458 ERROR 4384 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4384
hostname: xiaomo

2017-05-23 14:56:22,792 ERROR 4384 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4384
hostname: xiaomo

2017-05-23 14:56:48,432 ERROR 4384 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4384
hostname: xiaomo

2017-05-23 15:03:33,276 ERROR 4384 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4384
hostname: xiaomo

2017-05-23 15:04:26,066 ERROR 4384 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4384
hostname: xiaomo

2017-05-23 15:05:18,839 ERROR 4384 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4384
hostname: xiaomo

2017-05-23 15:05:42,878 ERROR 4384 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4384
hostname: xiaomo

2017-05-23 15:05:48,509 ERROR 4384 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4384
hostname: xiaomo

2017-05-23 15:28:15,142 ERROR 4384 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4384
hostname: xiaomo

2017-05-23 15:28:55,863 ERROR 4384 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4384
hostname: xiaomo

2017-05-23 15:36:06,223 ERROR 4384 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4384
hostname: xiaomo

2017-05-23 15:47:36,959 ERROR 4384 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4384
hostname: xiaomo

2017-05-23 15:52:41,493 ERROR 4384 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4384
hostname: xiaomo

2017-05-23 16:20:35,982 ERROR 4384 nodejs.unhandledExceptionError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4384
hostname: xiaomo

2017-05-23 16:35:45,426 ERROR 16732 [-/127.0.0.1/-/86ms POST /api/forum/followForum] nodejs.Error: Can't not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSTransaction.proto.update (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:152:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSTransaction.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    at RDSTransaction.createPromise [as update] (E:\nodejs\sumi-server\node_modules\co\index.js:30:15)
    at ForumService.followForum (E:\nodejs\sumi-server\app\service\forum.js:58:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 16732
hostname: xiaomo

2017-05-23 16:37:21,243 ERROR 17340 [-/127.0.0.1/-/35ms POST /api/forum/followForum] nodejs.Error: Can't not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSTransaction.proto.update (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:152:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSTransaction.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    at RDSTransaction.createPromise [as update] (E:\nodejs\sumi-server\node_modules\co\index.js:30:15)
    at ForumService.followForum (E:\nodejs\sumi-server\app\service\forum.js:53:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 17340
hostname: xiaomo

2017-05-23 16:38:22,742 ERROR 9480 [-/127.0.0.1/-/37ms POST /api/forum/followForum] nodejs.Error: Can't not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSTransaction.proto.update (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:152:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSTransaction.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    at RDSTransaction.createPromise [as update] (E:\nodejs\sumi-server\node_modules\co\index.js:30:15)
    at ForumService.followForum (E:\nodejs\sumi-server\app\service\forum.js:53:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 9480
hostname: xiaomo

2017-05-23 16:40:55,322 ERROR 15580 [-/127.0.0.1/-/51ms POST /api/forum/followForum] nodejs.TypeError: conn.rollback is not a function
    at ForumService.followForum (E:\nodejs\sumi-server\app\service\forum.js:57:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 15580
hostname: xiaomo

2017-05-23 16:40:57,573 ERROR 15580 [-/127.0.0.1/-/20ms POST /api/forum/followForum] nodejs.TypeError: conn.rollback is not a function
    at ForumService.followForum (E:\nodejs\sumi-server\app\service\forum.js:57:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 15580
hostname: xiaomo

2017-05-23 16:41:33,085 ERROR 16596 [-/127.0.0.1/-/44ms POST /api/forum/followForum] nodejs.Error: Can't not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSTransaction.proto.update (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:152:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSTransaction.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    at RDSTransaction.createPromise [as update] (E:\nodejs\sumi-server\node_modules\co\index.js:30:15)
    at ForumService.followForum (E:\nodejs\sumi-server\app\service\forum.js:53:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 16596
hostname: xiaomo

2017-05-23 16:42:25,989 ERROR 15404 [-/127.0.0.1/-/36ms POST /api/forum/followForum] nodejs.Error: Can't not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSTransaction.proto.update (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:152:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSTransaction.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    at RDSTransaction.createPromise [as update] (E:\nodejs\sumi-server\node_modules\co\index.js:30:15)
    at ForumService.followForum (E:\nodejs\sumi-server\app\service\forum.js:53:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 15404
hostname: xiaomo

2017-05-23 16:43:01,234 ERROR 14176 [-/127.0.0.1/-/34ms POST /api/forum/followForum] nodejs.Error: Can't not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSTransaction.proto.update (E:\nodejs\sumi-server\node_modules\ali-rds\lib\operator.js:152:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (E:\nodejs\sumi-server\node_modules\co\index.js:65:19)
    at E:\nodejs\sumi-server\node_modules\co\index.js:54:5
    at RDSTransaction.co (E:\nodejs\sumi-server\node_modules\co\index.js:50:10)
    at RDSTransaction.createPromise [as update] (E:\nodejs\sumi-server\node_modules\co\index.js:30:15)
    at ForumService.followForum (E:\nodejs\sumi-server\app\service\forum.js:53:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 14176
hostname: xiaomo

